language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - env: SPRING_BOOT_VERSION=2.0.3.RELEASE
  - env: SPRING_BOOT_VERSION=1.5.14.RELEASE
  - env: SPRING_BOOT_VERSION=1.4.7.RELEASE
