dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - env: SPRING_BOOT_VERSION=2.1.0.BUILD-SNAPSHOT
  - env: SPRING_BOOT_VERSION=2.0.3.RELEASE
  - env: SPRING_BOOT_VERSION=1.5.14.RELEASE
  - env: SPRING_BOOT_VERSION=1.4.7.RELEASE

install: true

script:
  - ./mvnw -U clean verify -Dspring-boot.version=${SPRING_BOOT_VERSION}
  - ./mvnw -U clean verify -Dspring-boot.version=${SPRING_BOOT_VERSION} -Ddozer.version=6.3.0-SNAPSHOT
